2022/08/21 23:48:31 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task.test.ru"
2022/08/21 23:48:31 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: 2022-08-22T02:48:31+03:00 [critical] Uncaught Exception: Unable to write in the "logs" directory (/test_task/var/log)" while reading upstream, client: 172.18.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task.test.ru"
2022/08/21 23:54:29 [error] 7#7: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://test_task.test.ru/"" at /test_task/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task.test.ru"
2022/08/21 23:54:30 [error] 7#7: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://test_task.test.ru/favicon.ico" (from "https://test_task.test.ru/")" at /test_task/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task.test.ru", referrer: "https://test_task.test.ru/"
2022/08/23 00:04:53 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 00:09:54 [error] 7#7: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 00:47:56 [error] 7#7: *14 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 00:47:58 [error] 7#7: *14 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/23 00:47:58 [error] 7#7: *14 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/23 01:04:32 [error] 7#7: *20 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 01:10:42 [error] 7#7: *24 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 01:10:43 [error] 7#7: *24 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/23 01:10:43 [error] 7#7: *24 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/23 15:38:19 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET //home_work_task_2 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 15:38:20 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task//home_work_task_2"
2022/08/23 15:38:20 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task//home_work_task_2"
2022/08/23 15:38:48 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_2 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 15:38:49 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_2"
2022/08/23 15:39:22 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_2 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 15:39:23 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_2"
2022/08/23 15:40:27 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_2 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 15:40:28 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_2"
2022/08/23 15:46:15 [error] 7#7: *15 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_1 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 15:46:16 [error] 7#7: *15 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_1"
2022/08/23 15:53:18 [error] 7#7: *20 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 15:59:10 [error] 7#7: *23 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 15:59:11 [error] 7#7: *23 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/23 15:59:11 [error] 7#7: *23 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/23 16:19:54 [error] 7#7: *29 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_2 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:19:55 [error] 7#7: *29 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_2"
2022/08/23 16:19:59 [error] 7#7: *29 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_3 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:20:50 [error] 7#7: *29 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_3 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:24:02 [crit] 7#7: *35 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.18.0.1, server: 0.0.0.0:443
2022/08/23 16:24:02 [crit] 7#7: *36 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.18.0.1, server: 0.0.0.0:443
2022/08/23 16:24:04 [error] 7#7: *37 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_3 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:24:05 [error] 7#7: *37 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_3"
2022/08/23 16:25:11 [error] 7#7: *37 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_3 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:25:12 [error] 7#7: *37 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_3"
2022/08/23 16:27:39 [error] 7#7: *37 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_3 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:27:40 [error] 7#7: *37 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_3"
2022/08/23 16:40:29 [error] 7#7: *46 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_3 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:40:30 [error] 7#7: *46 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_3"
2022/08/23 16:42:00 [error] 7#7: *46 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_3 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:42:01 [error] 7#7: *46 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_3"
2022/08/23 16:46:15 [error] 7#7: *53 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_3 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:46:16 [error] 7#7: *53 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_3"
2022/08/23 16:50:31 [crit] 7#7: *56 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.18.0.1, server: 0.0.0.0:443
2022/08/23 16:50:31 [crit] 7#7: *57 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.18.0.1, server: 0.0.0.0:443
2022/08/23 16:50:32 [error] 7#7: *58 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_3 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:50:33 [error] 7#7: *58 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_3"
2022/08/23 16:53:24 [error] 7#7: *58 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_3 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:53:25 [error] 7#7: *58 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_3"
2022/08/23 16:54:51 [error] 7#7: *58 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_2 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 16:54:52 [error] 7#7: *58 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_2"
2022/08/23 23:21:45 [error] 6#6: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /home_work_task_2 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task"
2022/08/23 23:21:47 [error] 6#6: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/stylesheets?v=1657531602&theme=auto HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_2"
2022/08/23 23:21:47 [error] 6#6: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.18.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.18.0.1, server: test_task, request: "GET /_debugbar/assets/javascript?v=1657531602 HTTP/2.0", upstream: "fastcgi://172.18.0.5:9000", host: "test_task", referrer: "https://test_task/home_work_task_2"
