2022/08/25 00:55:20 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task.localhost"
2022/08/25 00:57:32 [error] 7#7: *15 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/25 14:06:56 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/25 14:08:13 [error] 7#7: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/25 23:16:06 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 00:03:53 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 00:04:04 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 00:22:57 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 00:25:12 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 00:27:52 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 00:35:38 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 00:35:41 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /storage/images/logo.ico HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/26 00:40:18 [crit] 7#7: *12 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/26 00:40:18 [crit] 7#7: *13 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/26 00:40:20 [error] 7#7: *14 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 00:40:24 [error] 7#7: *14 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 00:54:39 [error] 7#7: *18 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 00:56:00 [error] 7#7: *18 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 00:56:24 [error] 7#7: *18 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 01:26:16 [error] 7#7: *24 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 01:29:47 [crit] 7#7: *26 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/26 01:29:47 [crit] 7#7: *27 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/26 01:29:49 [error] 7#7: *28 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 01:36:57 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 01:40:03 [crit] 7#7: *34 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/26 01:40:03 [crit] 7#7: *35 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/26 01:40:05 [error] 7#7: *36 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 01:41:14 [error] 7#7: *36 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 01:42:17 [error] 7#7: *36 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/26 01:50:10 [error] 7#7: *42 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:04:00 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:05:13 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:05:44 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:05:47 [error] 7#7: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /storage/images/logo.ico HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 03:09:41 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:10:38 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:10:51 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:11:23 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:13:24 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:14:02 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:14:40 [error] 7#7: *9 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:19:13 [error] 7#7: *19 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:20:02 [error] 7#7: *19 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:21:09 [error] 7#7: *19 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:21:39 [error] 7#7: *19 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 03:22:16 [error] 7#7: *19 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 04:17:34 [error] 7#7: *26 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 04:18:21 [error] 7#7: *26 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 04:19:38 [error] 7#7: *26 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 09:24:47 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:24:56 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 09:25:04 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:27:29 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 09:27:34 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/7 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:27:58 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 09:28:50 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 09:28:54 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/8 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:28:56 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:29:17 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/10 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:29:18 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:29:26 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:30:32 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:30:38 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/13 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:30:38 [error] 7#7: *32 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/13 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:43:35 [error] 7#7: *49 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 09:43:51 [error] 7#7: *49 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 09:43:56 [error] 7#7: *49 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/8 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:43:57 [error] 7#7: *49 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/8 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:47:03 [crit] 7#7: *53 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/27 09:47:03 [crit] 7#7: *54 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/27 09:47:05 [error] 7#7: *55 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/ HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 09:47:12 [error] 7#7: *55 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/13 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/"
2022/08/27 09:47:14 [error] 7#7: *55 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/"
2022/08/27 09:47:50 [error] 7#7: *55 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/"
2022/08/27 09:47:56 [error] 7#7: *55 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/6 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:47:58 [error] 7#7: *55 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:57:37 [error] 7#7: *64 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 09:57:41 [error] 7#7: *64 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 10:41:02 [error] 7#7: *69 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/ HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 10:41:17 [error] 7#7: *69 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/6 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/"
2022/08/27 10:45:36 [crit] 7#7: *72 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/27 10:45:36 [crit] 7#7: *73 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/27 10:45:38 [error] 7#7: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/6 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/"
2022/08/27 10:45:43 [error] 7#7: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/ HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 10:45:46 [error] 7#7: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 10:45:49 [error] 7#7: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 10:45:56 [error] 7#7: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/3/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 10:45:57 [error] 7#7: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/3/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 10:46:29 [error] 7#7: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/3/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 10:46:30 [error] 7#7: *74 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/3/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 10:50:29 [error] 7#7: *83 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 10:50:35 [error] 7#7: *83 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 10:50:41 [error] 7#7: *83 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/1/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 10:50:43 [error] 7#7: *83 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /_ignition/health-check HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/1/edit"
2022/08/27 10:51:12 [error] 7#7: *83 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 10:51:17 [error] 7#7: *83 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 10:57:35 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 10:57:42 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/7/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 10:57:44 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /_ignition/health-check HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/7/edit"
2022/08/27 11:00:41 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 11:00:46 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 11:00:53 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/5/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 11:02:10 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/5/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 11:02:11 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/5/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 11:02:40 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/5/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 11:03:24 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/5/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 11:04:51 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/5/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 11:05:36 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:08:04 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:08:05 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:08:51 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:08:52 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:10:06 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:10:07 [error] 7#7: *92 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:18:30 [error] 7#7: *109 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:18:32 [error] 7#7: *109 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/5/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:19:27 [error] 7#7: *109 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:19:36 [error] 7#7: *109 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:19:36 [error] 7#7: *109 FastCGI sent in stderr: ".1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:19:57 [error] 7#7: *109 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:20:36 [error] 7#7: *109 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/5 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:20:39 [error] 7#7: *109 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/5/edit"
2022/08/27 11:45:27 [error] 7#7: *119 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 11:47:12 [error] 7#7: *119 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 11:47:19 [error] 7#7: *119 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:07:28 [error] 7#7: *124 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 12:07:29 [error] 7#7: *124 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 12:07:40 [error] 7#7: *124 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:07:41 [error] 7#7: *124 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:19:53 [error] 7#7: *130 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:24:25 [crit] 7#7: *132 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/27 12:24:25 [crit] 7#7: *133 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/27 12:24:27 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:24:29 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:24:36 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:24:39 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:24:46 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:24:53 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?2 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:24:55 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:26:16 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:26:20 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:26:21 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:26:36 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:26:38 [error] 7#7: *134 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:30:24 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:30:36 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:30:38 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:30:59 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:31:04 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:31:06 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:31:15 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:31:17 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:32:22 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:32:26 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:32:28 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:34:49 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:34:55 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:35:03 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:35:52 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:35:53 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:36:21 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:36:22 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:36:49 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:36:49 [error] 7#7: *148 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?1 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:43:33 [error] 7#7: *167 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 12:43:45 [error] 7#7: *167 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?3 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:43:47 [error] 7#7: *167 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 12:43:59 [error] 7#7: *167 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 12:56:50 [error] 7#7: *174 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 12:57:17 [error] 7#7: *174 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 12:58:26 [error] 7#7: *174 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:01:41 [crit] 7#7: *178 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/27 13:01:41 [crit] 7#7: *179 SSL_do_handshake() failed (SSL: error:140944E7:SSL routines:ssl3_read_bytes:reason(1255):SSL alert number 255) while SSL handshaking, client: 172.19.0.1, server: 0.0.0.0:443
2022/08/27 13:01:43 [error] 7#7: *180 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:02:17 [error] 7#7: *180 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:02:55 [error] 7#7: *180 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:03:53 [error] 7#7: *180 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:04:58 [error] 7#7: *180 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:08:20 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:09:01 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:09:39 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:10:23 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:12:04 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:14:21 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:15:03 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:15:52 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:16:00 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/1/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:18:34 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/1/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:19:07 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/1/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:20:28 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/1/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:20:40 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 13:20:57 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/1/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:22:03 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/1/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:23:29 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/1/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:23:50 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/1/edit"
2022/08/27 13:25:06 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/1/edit"
2022/08/27 13:27:22 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/1/edit"
2022/08/27 13:27:44 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin/13 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:27:47 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:29:44 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:31:40 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:32:00 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/1/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:33:31 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/1/edit"
2022/08/27 13:33:41 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/1/edit"
2022/08/27 13:33:47 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/5/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 13:33:52 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/1/edit"
2022/08/27 13:33:57 [error] 7#7: *188 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/9/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 14:13:46 [error] 7#7: *220 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin/9/edit HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin"
2022/08/27 14:13:51 [error] 7#7: *220 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/admin/9/edit"
2022/08/27 14:13:59 [error] 7#7: *220 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 14:14:07 [error] 7#7: *220 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /admin?2 HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 14:14:09 [error] 7#7: *220 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/"
2022/08/27 14:22:50 [error] 7#7: *227 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 14:23:33 [error] 7#7: *231 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 14:25:48 [error] 7#7: *231 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 14:26:14 [error] 7#7: *234 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 14:38:04 [error] 7#7: *236 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 14:51:14 [error] 7#7: *238 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 14:51:16 [error] 7#7: *238 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/api/order"
2022/08/27 14:54:09 [error] 7#7: *241 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 14:54:10 [error] 7#7: *241 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task", referrer: "https://test_task/api/order"
2022/08/27 14:54:40 [error] 7#7: *241 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 14:56:35 [error] 7#7: *245 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order?buyers_id=1&products_id=1&products_price=1040.00&count_product=2 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 14:57:14 [error] 7#7: *245 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order?buyers_id=1&products_id=1&products_price=1040.00&count_product=2 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 14:59:51 [error] 7#7: *248 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order?buyers_id=1&products_id=1&products_price=1040.00&count_product=2 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:02:15 [error] 7#7: *250 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order?buyers_id=1&products_id=1&products_price=1040.00&count_product=2 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:03:35 [error] 7#7: *252 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order?buyers_id=1&products_id=1&products_price=1040.00&count_product=2 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:04:56 [error] 7#7: *254 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order?buyers_id=1&products_id=1&products_price=1040.00&count_product=2 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:05:27 [error] 7#7: *254 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order?buyers_id=1&products_id=1&products_price=1040.00&count_product=2 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:11:51 [error] 7#7: *257 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "DELETE /api/order?id=20 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:15:22 [error] 7#7: *259 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/20 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:19:46 [error] 7#7: *261 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:24:07 [error] 7#7: *263 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:25:22 [error] 7#7: *265 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/ HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:26:30 [error] 7#7: *265 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:27:22 [error] 7#7: *265 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:29:31 [error] 7#7: *269 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:29:44 [error] 7#7: *269 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:32:14 [error] 7#7: *272 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:32:55 [error] 7#7: *272 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:33:00 [error] 7#7: *272 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:34:20 [error] 7#7: *275 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:34:21 [error] 7#7: *275 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:36:59 [error] 7#7: *277 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:36:59 [error] 7#7: *277 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:37:35 [error] 7#7: *277 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:37:35 [error] 7#7: *277 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:39:08 [error] 7#7: *280 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:39:08 [error] 7#7: *280 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:41:32 [error] 7#7: *282 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:43:15 [error] 7#7: *284 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:43:15 [error] 7#7: *284 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:43:33 [error] 7#7: *284 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:44:08 [error] 7#7: *284 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:44:16 [error] 7#7: *284 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:44:31 [error] 7#7: *284 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "POST /api/order/19 HTTP/1.1", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
2022/08/27 15:51:25 [error] 7#7: *292 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.19.0.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: test_task, request: "GET /admin HTTP/2.0", upstream: "fastcgi://172.19.0.5:9000", host: "test_task"
